# Generated by Django 4.2.20 on 2025-04-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='analysis_mongo_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
